notifications:
  email: false

language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

script:
  - python setup.py build
  - python setup.py install
